Fix for python syntax error
 - since the file has non-ASCII characters, it can fail with a compile
   error if the doc type is not specified. This edit corrects for that.

`$ python ../SwiftPlate/testStructure.py test`

	File "testStructure.py", line 30
	SyntaxError: Non-ASCII character '\xe2' in file testStructure.py on line 30, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details